// PLN RUPTL Dashboard — Mock Project Data
// All Indonesian terminology preserved exactly as specified

const MOCK_PROJECTS = [
  // ─── EVACUATION CHAIN: Central Java ───────────────────────────────
  {
    id: "PRJ-001",
    name: "PLTMG Tambak Lorok Extension 150MW",
    type: "Power Plant",
    subtype: "PLTMG",
    ruptlCode: "RUPTL-JTG-PG-2024-001",
    status: "Construction",
    codTargetRUPTL: "Desember 2025",
    codKontraktual: "Maret 2026",
    codEstimasi: "Juni 2026",
    issueType: "Land Acquisition",
    progressPlan: 72,
    progressRealisasi: 68,
    deviasi: -4,
    urgencyCategory: ["Kehandalan Sistem", "RUPTL", "Evakuasi Daya"],
    relatedProjects: ["PRJ-002", "PRJ-003"],
    detail: "PLTMG 150MW di Semarang, Jawa Tengah. Proyek ini merupakan bagian dari rantai evakuasi daya Jawa Tengah untuk mendukung keandalan sistem 150kV.",
    latlng: [-6.970, 110.423],
    island: "Java",
    province: "Jawa Tengah",
    capacity: 150,
    capacityUnit: "MW",
    circuitLength: null,
    gridSystem: "Jawa-Madura-Bali (JAMALI)",
    voltageLevel: null
  },
  {
    id: "PRJ-002",
    name: "GI 150kV Tambak Lorok",
    type: "Substation",
    subtype: "GI 150kV",
    ruptlCode: "RUPTL-JTG-GI-2024-002",
    status: "Construction",
    codTargetRUPTL: "Oktober 2025",
    codKontraktual: "Oktober 2025",
    codEstimasi: "Desember 2025",
    issueType: "None",
    progressPlan: 81,
    progressRealisasi: 79,
    deviasi: -2,
    urgencyCategory: ["Kehandalan Sistem", "Evakuasi Daya"],
    relatedProjects: ["PRJ-001", "PRJ-003"],
    detail: "Gardu Induk 150kV di lokasi Tambak Lorok, Semarang. Menampung daya dari PLTMG dan menyalurkan ke jaringan transmisi 150kV.",
    latlng: [-6.975, 110.430],
    island: "Java",
    province: "Jawa Tengah",
    capacity: 60,
    capacityUnit: "MVA",
    circuitLength: null,
    gridSystem: "Jawa-Madura-Bali (JAMALI)",
    voltageLevel: "150kV"
  },
  {
    id: "PRJ-003",
    name: "SUTT 150kV Tambak Lorok – Srondol",
    type: "Transmission Line",
    subtype: "SUTT 150kV",
    ruptlCode: "RUPTL-JTG-TL-2024-003",
    status: "Pre-Construction",
    codTargetRUPTL: "Desember 2025",
    codKontraktual: "Maret 2026",
    codEstimasi: "September 2026",
    issueType: "ROW",
    progressPlan: 35,
    progressRealisasi: 22,
    deviasi: -13,
    urgencyCategory: ["RUPTL", "Kerawanan Sistem", "Evakuasi Daya"],
    relatedProjects: ["PRJ-001", "PRJ-002", "PRJ-004"],
    detail: "Jalur transmisi SUTT 150kV sepanjang 28km menghubungkan GI Tambak Lorok ke GI Srondol. Hambatan utama: pembebasan lahan ROW di kawasan padat.",
    latlng: [-7.010, 110.405],
    island: "Java",
    province: "Jawa Tengah",
    capacity: null,
    capacityUnit: null,
    circuitLength: 28,
    gridSystem: "Jawa-Madura-Bali (JAMALI)",
    voltageLevel: "150kV",
    lineFrom: "PRJ-002",
    lineTo: "PRJ-004"
  },
  {
    id: "PRJ-004",
    name: "GI 150kV Srondol",
    type: "Substation",
    subtype: "GI 150kV",
    ruptlCode: "RUPTL-JTG-GI-2024-004",
    status: "Energized",
    codTargetRUPTL: "Maret 2023",
    codKontraktual: "Maret 2023",
    codEstimasi: "Maret 2023",
    issueType: "None",
    progressPlan: 100,
    progressRealisasi: 100,
    deviasi: 0,
    urgencyCategory: ["Kehandalan Sistem"],
    relatedProjects: ["PRJ-003"],
    detail: "GI 150kV Srondol telah beroperasi dan melayani beban Semarang Selatan dan sekitarnya.",
    latlng: [-7.048, 110.388],
    island: "Java",
    province: "Jawa Tengah",
    capacity: 60,
    capacityUnit: "MVA",
    circuitLength: null,
    gridSystem: "Jawa-Madura-Bali (JAMALI)",
    voltageLevel: "150kV"
  },

  // ─── SUMATRA ──────────────────────────────────────────────────────
  {
    id: "PRJ-005",
    name: "PLTU Sumsel 8 2×350MW",
    type: "Power Plant",
    subtype: "PLTU",
    ruptlCode: "RUPTL-SML-PG-2024-005",
    status: "Construction",
    codTargetRUPTL: "Juni 2025",
    codKontraktual: "Desember 2025",
    codEstimasi: "Maret 2026",
    issueType: "Permitting",
    progressPlan: 88,
    progressRealisasi: 82,
    deviasi: -6,
    urgencyCategory: ["RUPTL", "Penurunan BPP", "Kehandalan Sistem"],
    relatedProjects: ["PRJ-006"],
    detail: "PLTU batubara kapasitas 2×350MW di Sumatera Selatan. Proyek strategis nasional untuk pemenuhan beban Sumatera.",
    latlng: [-3.290, 103.880],
    island: "Sumatra",
    province: "Sumatera Selatan",
    capacity: 700,
    capacityUnit: "MW",
    circuitLength: null,
    gridSystem: "Sumatera Bagian Selatan",
    voltageLevel: null
  },
  {
    id: "PRJ-006",
    name: "SUTET 500kV Sumsel 8 – Muara Enim",
    type: "Transmission Line",
    subtype: "SUTET 500kV",
    ruptlCode: "RUPTL-SML-TL-2024-006",
    status: "Pre-Construction",
    codTargetRUPTL: "Juni 2025",
    codKontraktual: "September 2025",
    codEstimasi: "Desember 2025",
    issueType: "ROW",
    progressPlan: 42,
    progressRealisasi: 28,
    deviasi: -14,
    urgencyCategory: ["RUPTL", "Evakuasi Daya", "Kerawanan Sistem"],
    relatedProjects: ["PRJ-005", "PRJ-007"],
    detail: "Jalur SUTET 500kV sepanjang 65km dari PLTU Sumsel 8 ke GIS 500kV Muara Enim. Hambatan utama: ROW lintas kawasan hutan.",
    latlng: [-3.470, 103.820],
    island: "Sumatra",
    province: "Sumatera Selatan",
    capacity: null,
    capacityUnit: null,
    circuitLength: 65,
    gridSystem: "Sumatera Bagian Selatan",
    voltageLevel: "500kV",
    lineFrom: "PRJ-005",
    lineTo: "PRJ-007"
  },
  {
    id: "PRJ-007",
    name: "GIS 500kV Muara Enim",
    type: "Substation",
    subtype: "GIS 500kV",
    ruptlCode: "RUPTL-SML-GI-2024-007",
    status: "Construction",
    codTargetRUPTL: "September 2025",
    codKontraktual: "Desember 2025",
    codEstimasi: "Maret 2026",
    issueType: "None",
    progressPlan: 64,
    progressRealisasi: 61,
    deviasi: -3,
    urgencyCategory: ["RUPTL", "Kehandalan Sistem"],
    relatedProjects: ["PRJ-006"],
    detail: "GIS 500kV di Muara Enim sebagai simpul utama transmisi backbone Sumatera.",
    latlng: [-3.660, 103.755],
    island: "Sumatra",
    province: "Sumatera Selatan",
    capacity: 500,
    capacityUnit: "MVA",
    circuitLength: null,
    gridSystem: "Sumatera Bagian Selatan",
    voltageLevel: "500kV"
  },

  // ─── KALIMANTAN ───────────────────────────────────────────────────
  {
    id: "PRJ-008",
    name: "PLTS Kalimantan Timur 50MWp",
    type: "Power Plant",
    subtype: "PLTS",
    ruptlCode: "RUPTL-KLT-PG-2024-008",
    status: "Pre-Construction",
    codTargetRUPTL: "Desember 2026",
    codKontraktual: "Desember 2026",
    codEstimasi: "Maret 2027",
    issueType: "None",
    progressPlan: 18,
    progressRealisasi: 15,
    deviasi: -3,
    urgencyCategory: ["Pemenuhan EBT", "RUPTL"],
    relatedProjects: ["PRJ-009"],
    detail: "Pembangkit Listrik Tenaga Surya 50MWp di Kalimantan Timur untuk mendukung target EBT nasional dan kebutuhan IKN.",
    latlng: [-1.240, 116.852],
    island: "Kalimantan",
    province: "Kalimantan Timur",
    capacity: 50,
    capacityUnit: "MW",
    circuitLength: null,
    gridSystem: "Kalimantan Timur",
    voltageLevel: null
  },
  {
    id: "PRJ-009",
    name: "GI 150kV Balikpapan Baru",
    type: "Substation",
    subtype: "GI 150kV",
    ruptlCode: "RUPTL-KLT-GI-2024-009",
    status: "Construction",
    codTargetRUPTL: "Juni 2026",
    codKontraktual: "Juni 2026",
    codEstimasi: "September 2026",
    issueType: "None",
    progressPlan: 45,
    progressRealisasi: 48,
    deviasi: 3,
    urgencyCategory: ["Demand KTT", "RUPTL"],
    relatedProjects: ["PRJ-008"],
    detail: "GI 150kV baru di Balikpapan untuk mendukung pertumbuhan beban IKN (Ibu Kota Nusantara).",
    latlng: [-1.265, 116.875],
    island: "Kalimantan",
    province: "Kalimantan Timur",
    capacity: 60,
    capacityUnit: "MVA",
    circuitLength: null,
    gridSystem: "Kalimantan Timur",
    voltageLevel: "150kV"
  },

  // ─── SULAWESI ─────────────────────────────────────────────────────
  {
    id: "PRJ-010",
    name: "PLTGU Sulawesi Selatan 500MW",
    type: "Power Plant",
    subtype: "PLTGU",
    ruptlCode: "RUPTL-SLS-PG-2024-010",
    status: "Energized",
    codTargetRUPTL: "Juni 2024",
    codKontraktual: "Juni 2024",
    codEstimasi: "Juni 2024",
    issueType: "None",
    progressPlan: 100,
    progressRealisasi: 100,
    deviasi: 0,
    urgencyCategory: ["Kehandalan Sistem", "Penurunan BPP"],
    relatedProjects: ["PRJ-011"],
    detail: "PLTGU 500MW di Sulawesi Selatan sudah beroperasi penuh. Menjadi backbone pasokan listrik Sulawesi Selatan-Tenggara.",
    latlng: [-5.130, 119.420],
    island: "Sulawesi",
    province: "Sulawesi Selatan",
    capacity: 500,
    capacityUnit: "MW",
    circuitLength: null,
    gridSystem: "Sulawesi Selatan-Tenggara",
    voltageLevel: null
  },
  {
    id: "PRJ-011",
    name: "SUTT 150kV Makassar Ring",
    type: "Transmission Line",
    subtype: "SUTT 150kV",
    ruptlCode: "RUPTL-SLS-TL-2024-011",
    status: "Construction",
    codTargetRUPTL: "Maret 2026",
    codKontraktual: "Juni 2026",
    codEstimasi: "September 2026",
    issueType: "Land Acquisition",
    progressPlan: 55,
    progressRealisasi: 47,
    deviasi: -8,
    urgencyCategory: ["Kehandalan Sistem", "Evakuasi Daya"],
    relatedProjects: ["PRJ-010"],
    detail: "Ring transmisi 150kV mengelilingi metropolitan Makassar. Hambatan: pembebasan lahan di kawasan padat perkotaan.",
    latlng: [-5.170, 119.450],
    island: "Sulawesi",
    province: "Sulawesi Selatan",
    capacity: null,
    capacityUnit: null,
    circuitLength: 40,
    gridSystem: "Sulawesi Selatan-Tenggara",
    voltageLevel: "150kV",
    lineFrom: "PRJ-010",
    lineTo: "PRJ-010"
  },

  // ─── PAPUA ────────────────────────────────────────────────────────
  {
    id: "PRJ-012",
    name: "PLTM Sentani 2×10MW",
    type: "Power Plant",
    subtype: "PLTM",
    ruptlCode: "RUPTL-PAP-PG-2024-012",
    status: "Pre-Construction",
    codTargetRUPTL: "Juni 2027",
    codKontraktual: "Desember 2027",
    codEstimasi: "Maret 2028",
    issueType: "Permitting",
    progressPlan: 8,
    progressRealisasi: 5,
    deviasi: -3,
    urgencyCategory: ["Kerawanan Sistem", "Pemenuhan EBT", "RUPTL"],
    relatedProjects: [],
    detail: "PLTM 2×10MW di area Sentani, Papua. Proyek EBT untuk mengurangi ketergantungan PLTD di sistem kelistrikan Papua.",
    latlng: [-2.576, 140.518],
    island: "Papua",
    province: "Papua",
    capacity: 20,
    capacityUnit: "MW",
    circuitLength: null,
    gridSystem: "Papua",
    voltageLevel: null
  },

  // ─── NUSA TENGGARA ────────────────────────────────────────────────
  {
    id: "PRJ-013",
    name: "PLTS Lombok 25MWp",
    type: "Power Plant",
    subtype: "PLTS",
    ruptlCode: "RUPTL-NTB-PG-2024-013",
    status: "Construction",
    codTargetRUPTL: "Juni 2025",
    codKontraktual: "September 2025",
    codEstimasi: "Desember 2025",
    issueType: "None",
    progressPlan: 78,
    progressRealisasi: 82,
    deviasi: 4,
    urgencyCategory: ["Pemenuhan EBT", "Kehandalan Sistem"],
    relatedProjects: [],
    detail: "PLTS 25MWp di Lombok NTB. Progres di atas target — diperkirakan selesai lebih awal dari jadwal.",
    latlng: [-8.650, 116.350],
    island: "Nusa Tenggara",
    province: "Nusa Tenggara Barat",
    capacity: 25,
    capacityUnit: "MW",
    circuitLength: null,
    gridSystem: "Nusa Tenggara",
    voltageLevel: null
  }
];


const PROVINCE_OPTIONS = [
  "Jawa Tengah",
  "Sumatera Selatan",
  "Kalimantan Timur",
  "Sulawesi Selatan",
  "Papua",
  "Nusa Tenggara Barat"
];

const URGENCY_OPTIONS = [
  "Kehandalan Sistem",
  "RUPTL",
  "Penurunan BPP",
  "Pemenuhan EBT",
  "Kerawanan Sistem",
  "Demand KTT",
  "Evakuasi Daya"
];

const STATUS_CONFIG = {
  "Energized":        { color: "#10B981", bg: "rgba(16,185,129,0.12)", glow: "rgba(16,185,129,0.5)" },
  "Construction":     { color: "#F59E0B", bg: "rgba(245,158,11,0.12)",  glow: "rgba(245,158,11,0.5)" },
  "Pre-Construction": { color: "#3B82F6", bg: "rgba(59,130,246,0.12)",  glow: "rgba(59,130,246,0.5)" },
  "Issue":            { color: "#EF4444", bg: "rgba(239,68,68,0.12)",   glow: "rgba(239,68,68,0.5)" },
};

const TYPE_CONFIG = {
  "Power Plant":       { shape: "circle",  size: 10, baseColor: "#10B981" },
  "Substation":        { shape: "diamond", size: 10, baseColor: "#0E91A5" },
  "Transmission Line": { shape: "line",    size: 6,  baseColor: "#3B82F6" },
};

Object.assign(window, { MOCK_PROJECTS, URGENCY_OPTIONS, PROVINCE_OPTIONS, STATUS_CONFIG, TYPE_CONFIG });
