import { IsString, IsNumber, IsOptional, IsArray, IsEnum, IsDateString, Min, Max } from 'class-validator';
import { Type } from 'class-transformer';
import { ProjectType, ProjectStage } from '@prisma/client';

export class CreateProjectDto {
  @IsString()                                   name:              string;
  @IsEnum(ProjectType)                          type:              ProjectType;
  @IsOptional() @IsString()                     subtype?:          string;
  @IsString()                                   ruptlCode:         string;
  @IsEnum(ProjectStage)                         stage:             ProjectStage;
  @IsOptional() @IsString()                     status?:           string;
  @IsOptional() @IsString()                     priority?:         string;
  @IsOptional() @IsString()                     codTargetRUPTL?:   string;
  @IsOptional() @IsString()                     codKontraktual?:   string;
  @IsOptional() @IsString()                     codEstimasi?:      string;
  @IsOptional() @IsString()                     issueType?:        string;
  @IsOptional() @IsString()                     issueStrategic?:   string;
  @IsOptional() @Type(() => Number) @IsNumber() @Min(0) @Max(100)  progressPlan?:      number;
  @IsOptional() @Type(() => Number) @IsNumber() @Min(0) @Max(100)  progressRealisasi?: number;
  @IsOptional() @Type(() => Number) @IsNumber() @Min(-100) @Max(100) deviasi?:         number;
  @IsOptional() @Type(() => Number) @IsNumber() lat?:              number;
  @IsOptional() @Type(() => Number) @IsNumber() lng?:              number;
  @IsOptional() @IsString()                     island?:           string;
  @IsOptional() @IsString()                     region?:           string;
  @IsOptional() @IsString()                     province?:         string;
  @IsOptional() @IsString()                     gridSystem?:       string;
  @IsOptional() @Type(() => Number) @IsNumber() capacity?:         number;
  @IsOptional() @IsString()                     capacityUnit?:     string;
  @IsOptional() @Type(() => Number) @IsNumber() circuitLength?:    number;
  @IsOptional() @IsString()                     voltageLevel?:     string;
  @IsOptional() @IsString()                     lineFromId?:       string;
  @IsOptional() @IsString()                     lineToId?:         string;
  @IsOptional() @IsString()                     notification?:     string;
  @IsOptional() @IsString()                     bpoNotes?:         string;
  @IsOptional() @IsDateString()                 bpoLastModified?:  string;
  @IsOptional() @IsString()                     comment?:          string;
  @IsOptional() @IsString()                     detail?:           string;
  @IsOptional() @IsArray() @IsString({ each: true }) urgencyCategory?: string[];
  @IsOptional() @IsArray() @IsString({ each: true }) relatedProjects?: string[];
}
